EnglishCourse.WEB/Controllers/AnswerController.cs
using System.Linq;
using EnglishCourse.Logic.Interfaces;
using EnglishCourse.Model.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EnglishCourse.WEB.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AnswerController : Controller
    {
        private readonly IAnswerService _answerService;
        private readonly IQuestionService _questionService;
        
        public AnswerController(IAnswerService answerService, IQuestionService questionService)
        {
            _answerService = answerService;
            _questionService = questionService;
        }

        public IActionResult Index()
        {
            return View(_answerService.GetAll());
        }

        public IActionResult Create()
        {
            ViewBag.QuestionList = _questionService.GetAll();

            return View();
        }

        [HttpPost]
        public IActionResult Create(AnswerVM model)
        {
            if (ModelState.IsValid)
            {
                var answer = _answerService.GetAll().Where(x => x.QuestionId == model.QuestionId && x.Text == model.Text).FirstOrDefault();

                if(answer == null)
                {
                    int count = _answerService.GetAll().Where(x => x.QuestionId == model.QuestionId && x.IsRight == true && x.IsRight == model.IsRight).Count();

                    if (count == 0)
                    {
                        _answerService.Create(model);

                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "The right answer to this question already has!");
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "The answer to this question already has!");
                }                
            }

            ViewBag.QuestionList = _questionService.GetAll();

            return View();
        }

        public IActionResult Delete(int id)
        {
            AnswerVM answer = _answerService.GetById(id);

            return View(answer);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirm(int id)
        {
            AnswerVM answer = _answerService.GetById(id);

            _answerService.Delete(answer.AnswerId);

            return RedirectToAction("Index");
        }
    }
}

EnglishCourse.WEB/Controllers/QuestionController.cs
using EnglishCourse.Logic.Interfaces;
using EnglishCourse.Model.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace EnglishCourse.WEB.Controllers
{
    [Authorize(Roles = "Admin")]
    public class QuestionController : Controller
    {
        private readonly IQuestionService _questionRepository;
        private readonly ITestService _testRepository;

        public QuestionController(IQuestionService questionRepository, ITestService testRepository)
        {
            _questionRepository = questionRepository;
            _testRepository = testRepository;
        }

        public IActionResult Index()
        {
            return View(_questionRepository.GetAll());
        }

        public IActionResult Create()
        {
            ViewBag.TestList = _testRepository.GetAll();

            return View();
        }

        [HttpPost]
        public IActionResult Create(QuestionVM model)
        {
            if (ModelState.IsValid)
            {
                var question = _questionRepository.GetAll().Where(x => x.TestId == model.TestId && x.Text == model.Text).FirstOrDefault();

                if (question == null)
                {
                    _questionRepository.Create(model);

                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "This question is already exists");
                }
            }

            ViewBag.TestList = _testRepository.GetAll();

            return View(model);
        }

        public IActionResult Edit(int id)
        {
            QuestionVM question = _questionRepository.GetById(id);

            ViewBag.TestList = _testRepository.GetAll();

            return View(question);
        }

        [HttpPost]
        public IActionResult Edit(QuestionVM model)
        {
            if (ModelState.IsValid)
            {
                var question = _questionRepository.GetAll().Where(x => x.TestId == model.TestId && x.Text == model.Text && x.Score == model.Score).FirstOrDefault();

                if (question == null)
                {
                    _questionRepository.Update(model);

                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Data not changed");
                }
            }

            ViewBag.TestList = _testRepository.GetAll();

            return View(model);
        }

        public IActionResult Delete(int id)
        {
            QuestionVM question = _questionRepository.GetById(id);

            return View(question);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirm(int id)
        {
            QuestionVM question = _questionRepository.GetById(id);

            _questionRepository.Delete(question.QuestionId);

            return RedirectToAction("Index");
        }
    }
}

EnglishCourse.WEB/Controllers/TestController.cs
using EnglishCourse.Logic.Interfaces;
using EnglishCourse.Model.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace EnglishCourse.WEB.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TestController : Controller
    {
        private readonly IThemeService _themeService;
        private readonly ITestService _testService;

        public TestController(IThemeService themeService, ITestService testService)
        {
            _themeService = themeService;
            _testService = testService;
        }

        public IActionResult Index()
        {
            IEnumerable<ThemeVM> themes = _themeService.GetAll();
            ViewBag.ThemeList = themes;

            return View(new TestVM());
        }
    }
}

EnglishCourse.WEB/Controllers/ThemeController.cs
using EnglishCourse.Logic.Interfaces;
using EnglishCourse.Model.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EnglishCourse.WEB.Controllers
{
    public class ThemeController : Controller
    {
        private readonly IThemeService _themeService;

        public ThemeController(IThemeService themeService)
        {
            _themeService = themeService;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View(new ThemeVM());
        }

        [AllowAnonymous]
        public IActionResult Details(int id)
        {
            ThemeVM theme = _themeService.GetById(id);

            return View(theme);
        }

        //[Authorize(Roles = "User")]
        //public IActionResult Favorite(int id)
        //{
        //    ThemeVM theme = _themeService.GetById(id);

        //    return View(theme);
        //}
    }
}

EnglishCourse.WEB/Views/Shared/_AdminPart.cshtml
@model EnglishCourse.Model.ViewModels.HomeVM

<div class="row" style="margin-top:5px">
    <div style="margin-left:35%">
        <h2><b>Административная часть</b></h2>
    </div>
    <div class="col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Theme Count
            </div>
            <div class="panel-body">
                There are @Model.ThemeCount themes

                <div class="btn-group">
                    <a class="btn btn-info" asp-area="" asp-controller="Theme" asp-action="Index">List of themes</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Test Count
            </div>
            <div class="panel-body">
                There are @Model.TestCount tests

                <div class="btn-group">
                    <a class="btn btn-info" asp-area="" asp-controller="Test" asp-action="Index">List of tests</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Question count
            </div>
            <div class="panel-body">
                There are @Model.QuestionCount questions

                <div class="btn-group">
                    <a class="btn btn-info" asp-area="" asp-controller="Question" asp-action="Index">List of questions</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                Answer count
            </div>
            <div class="panel-body">
                There are @Model.AnswerCount answers

                <div class="btn-group">
                    <a class="btn btn-info" asp-area="" asp-controller="Answer" asp-action="Index">List of answers</a>
                </div>
            </div>
        </div>
    </div>
</div>

EnglishCourse.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

@inject EnglishCourse.Logic.Interfaces.IAccountService _accountService

<html >
<head >
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EnglishCourse</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <script src="~/js/jquery.serializejson.js"></script>
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

</head>
<body class="bd">
    
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">EnglishCourse</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        var role = _accountService.GetRole(User.Identity.Name);

                        if (role == "Admin")
                        {
                            <li><a asp-controller="Theme" asp-action="Index">Theme</a></li>
                            <li><a asp-controller="Test" asp-action="Index">Test</a></li>
                            <li><a asp-controller="Question" asp-action="Index">Question</a></li>
                            <li><a asp-controller="Answer" asp-action="Index">Answer</a></li>
                        }
                        else if (role == "User")
                        {
                            <li><a asp-controller="Account" asp-action="MyProfile">Профиль|Profile</a></li>
                            <li><a asp-controller="Account" asp-action="About">О нас|About Us</a></li>
                            <li><a asp-controller="Account" asp-action="Contacts">Контакты|Contacts</a></li>
                        }
                    }
                </ul>
                <div class="nav navbar-nav" style="margin-top:10px; float:right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a style="cursor:pointer;margin-right:5px">Dear: @User.Identity.Name</a>
                        <a asp-area="" asp-controller="Account" asp-action="Logout" class="btn btn-danger">Logout</a>
                    }
                    else
                    {
                        <a asp-area="" asp-controller="Account" asp-action="Login" class="btn btn-success">Sign in</a>
                        <a asp-area="" asp-controller="Account" asp-action="Registration" class="btn btn-primary">Sign up</a>
                    }
                </div>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - EnglishCourse.WEB</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

EnglishCourse.WEB/Views/Shared/_QuestionPartial.cshtml
@model EnglishCourse.Model.ViewModels.QuestionVM

@inject EnglishCourse.Logic.Interfaces.IAnswerService _answerService

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="panel panel-primary">
        <div class="panel panel-heading">
            <p>@Model.Text</p>
        </div>
        <div class="panel-body">
            <div class="btn-group">
                @{
                    var answers = _answerService.GetAll().Where(x => x.QuestionId == Model.QuestionId).ToList();

                    for (int i = 0; i < answers.Count(); i++)
                    {
                        <input type="radio" name="@Model.QuestionId" value="@answers[i].Text" /> @answers[i].Text
                        <br />
                    }
                }
            </div>
        </div>
    </div>
</div>

EnglishCourse.WEB/Views/Shared/_UserPart.cshtml
@using EnglishCourse.Model.ViewModels
@model ThemeVM
@{
    string description = Model.Description;

    @if (description.Length > 100)
    {
        description = description.Substring(0, 100) + "...";
    }
    else if (description.Length < 50)
    {
        description = description.Substring(0, 40) + "...";
    }
    else if (description.Length < 10)
    {
        description = description.Substring(0, 8) + "...";
    }
    else if (description.Length < 5)
    {
        description = description.Substring(0, 4) + "...";
    }
}

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="panel panel-primary">
        <div class="panel panel-heading">
            <p>@Model.Name</p>
        </div>
        <div class="panel-body">
            <div style="margin-bottom:15px">
                @description
            </div>
            <div class="btn-group">
                <a class="btn btn-info" asp-area="" asp-controller="Theme" asp-action="Details" asp-route-id="@Model.ThemeId">Details Theme</a>
                <a class="btn btn-danger" asp-area="" asp-controller="Home" asp-action="Tests" asp-route-id="@Model.ThemeId">Tests</a>
            </div>
        </div>
    </div>
</div>